export function getHookScript(hookType: 'pre-commit' | 'pre-push', npxPath: string): string {
  return `#!/bin/sh
# .git/hooks/${hookType}
# Auto-generated by RuleGen — do not edit manually
# https://github.com/sutheesh/rulegen

# Run RuleGen scan (< 2 seconds, local only, no network)
${npxPath} rulegen --hook 2>/dev/null || true

# Stage any updated rules files
git add -f CLAUDE.md .cursorrules .github/copilot-instructions.md .windsurfrules AGENTS.md 2>/dev/null || true

# Always exit 0 — never block a commit because of rules generation
exit 0
`;
}
